services:
  crowdsec:
    image: ${CROWDSEC_IMAGE_TAG:-crowdsecurity/crowdsec:latest}
    container_name: crowdsec
    restart: unless-stopped
    environment:
      TZ: Asia/Yekaterinburg
      COLLECTIONS: "crowdsecurity/linux a1ad/mikrotik crowdsecurity/traefik" # crowdsecurity/nginx fulljackz/proxmox 
      # ENROLL_KEY: "clomgynlexampletokenn3cd" # Uncomment and insert your token if you want crowdsec dashboard https://app.crowdsec.net
      # ENROLL_INSTANCE_NAME: "homelab" # Uncomment if you want https://app.crowdsec.net
    ports:
      - 8080:8080
      - 6060:6060
    volumes:
      - ./crowdsec/data:/var/lib/crowdsec/data
      - ./crowdsec/config:/etc/crowdsec
    healthcheck:
      test: ["CMD", "cscli", "version"]
      start_period: 10s
    networks:
      crowdsec_net:
        ipv4_address: 172.21.0.10

  blocklist:
    image: ${CROWDSEC_BLOCKLIST_IMAGE_TAG:-crowdsecurity/blocklist-mirror:latest}
    container_name: blocklist
    restart: unless-stopped
    depends_on:
      crowdsec:
        condition: service_healthy
    environment:
      TZ: Asia/Yekaterinburg
      API_KEY: ${API_KEY:-'UseCrowdSecAPIKey'}
    ports:
      - 41412:41412
    volumes:
      - ./blocklist_config.yaml:/etc/crowdsec/bouncers/crowdsec-blocklist-mirror.yaml
    healthcheck:
      test: wget -qO- http://localhost:41412/security/blocklist?ipv4only || exit 1
      start_period: 20s
      interval: 5s
      timeout: 3s
      retries: 5
    networks:
      crowdsec_net:
        ipv4_address: 172.21.0.12

  mikroseclist:
    image: ${MIKROSECLIST_IMAGE_TAG:-ghcr.io/akmalovaa/mikroseclist:latest}
    container_name: mikroseclist
    depends_on:
      blocklist:
        condition: service_healthy
        restart: true
      crowdsec:
        condition: service_started
    command: ["python", "-m", "mikroseclist.main"]
    environment:
      MIKROTIK_HOST: ${MIKROTIK_HOST:-'192.168.88.1'}
      MIKROTIK_USER: ${MIKROTIK_USER:-'admin'}
      MIKROTIK_PASSWORD: ${MIKROTIK_PASSWORD:-'password'}
      BLOCKLIST_URL: 'http://blocklist:41412/security/blocklist?ipv4only'
      SYNC_INTERVAL_MIN: 15
    restart: unless-stopped
    networks:
      crowdsec_net:
        ipv4_address: 172.21.0.13

networks:
  crowdsec_net:
    driver: bridge
    ipam:
      config:
        - subnet: 172.21.0.0/24
          gateway: 172.21.0.1