services:
  mikroseclist:
    image: mikroseclist:latest
    build:
      context: .
      dockerfile: Dockerfile 
    container_name: mikroseclist
    command: ["python", "-m", "mikroseclist.main"]
    # command: ["tail", "-f", "/dev/null"]
    environment:
      LOG_LEVEL: DEBUG
      MIKROTIK_HOST: ${MIKROTIK_HOST:-'192.168.88.1'}
      MIKROTIK_USER: ${MIKROTIK_USER:-'admin'}
      MIKROTIK_PASSWORD: ${MIKROTIK_PASSWORD:-'password'}
      BLOCKLIST_URL: ${BLOCKLIST_URL}
      SYNC_INTERVAL_MIN: 2
    volumes:
      - ./:/srv/
    restart: on-failure
