version: '3'

env:
  IMAGE_TAG: 'mikroseclist:latest'

tasks:
  cli:
    aliases: [bash, shell, exec]
    desc: run temporary container and passthrough current directory
    cmds:
      - docker run --rm -it --env-file .env -v .:/srv $IMAGE_TAG bash

  build:
    cmds:
      - docker build . -t $IMAGE_TAG

# export PYTHONPATH='/srv/mikroseclist/'
# python -m mikroseclist.main